scrape_configs:
  - job_name: 'McsOrder'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['35.223.160.67:80']
        labels:
          application: 'McsOrder'