name: PMD Security Analysis

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  contents: read
  security-events: write

jobs:
  pmd:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run PMD Analysis
        run: |
          ./gradlew pmdMain
          mv build/reports/pmd/main.xml pmd-report.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'pmd-report.sarif'
